// ─── Application Configuration ─────────────────────────────────────
// Replace these values with your actual Supabase project credentials
// and backend URL before deploying.

function publicEnv(name, fallback) {
  const value = window.__ENV__?.[name];
  return value && !value.startsWith("%VITE_") ? value : fallback;
}

const CONFIG = {
  // Live AI OCR scanning, statutory auditing, and dynamic reports
  IS_LIVE: true,

  // Supabase project settings (from https://app.supabase.com → Settings → API)
  SUPABASE_URL: publicEnv('SUPABASE_URL', ''),
  SUPABASE_ANON_KEY: publicEnv('SUPABASE_ANON_KEY', ''),

  // Backend API Base URL (empty uses current host /api/*)
  API_BASE_URL: publicEnv('API_BASE_URL', ''),

  // Supabase Storage bucket names
  BUCKETS: {
    LABEL_IMAGES: 'label-images',
    REPORTS: 'compliance-reports',
  },

  // App version
  VERSION: '2.1',
  APP_NAME: 'PRISM (Packaged Rules Inspection & Scanning Mechanism)',
};

// ─── Language map ───────────────────────────────────────────────────
const LANGUAGES = [
  { code: 'en',  label: 'English',   native: 'English' },
  { code: 'hi',  label: 'Hindi',     native: 'हिन्दी' },
  { code: 'bn',  label: 'Bengali',   native: 'বাংলা' },
  { code: 'te',  label: 'Telugu',    native: 'తెలుగు' },
  { code: 'mr',  label: 'Marathi',   native: 'मराठी' },
  { code: 'ta',  label: 'Tamil',     native: 'தமிழ்' },
  { code: 'ur',  label: 'Urdu',      native: 'اردو' },
  { code: 'gu',  label: 'Gujarati',  native: 'ગુજરાતી' },
  { code: 'kn',  label: 'Kannada',   native: 'ಕನ್ನಡ' },
  { code: 'ml',  label: 'Malayalam', native: 'മലയാളം' },
  { code: 'pa',  label: 'Punjabi',   native: 'ਪੰਜਾਬੀ' },
];

// ─── i18n strings ───────────────────────────────────────────────────
const STRINGS = {
  en: {
    'app.name': 'PRISM (Packaged Rules Inspection & Scanning Mechanism)',
    'nav.dashboard': 'Dashboard',
    'nav.scanner': 'Label Scanner',
    'nav.repository': 'Repository',
    'nav.reports': 'Reports',
    'nav.users': 'User Management',
    'nav.settings': 'Settings',
    'nav.logout': 'Log Out',
    'common.loading': 'Loading…',
    'common.error': 'Something went wrong.',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.download': 'Download',
    'common.export': 'Export',
    'common.search': 'Search…',
    'common.filter': 'Filter',
    'common.refresh': 'Refresh',
    'login.heading': 'Select Your Role',
    'login.subheading': 'Each role has a separate dashboard and access level.',
    'login.features': 'Platform Capabilities',
    'login.footer': 'Legal Metrology Act, 2009 · LM (PC) Rules, 2011 · Government of India',
    'login.userId': 'User ID',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.back': 'Back to role selection',
    'login.mobile': 'Mobile Number',
    'login.sendOtp': 'Send OTP',
    'login.verifyOtp': 'Verify & Sign In',
    'login.resendOtp': 'Resend OTP',
    'login.enterOtp': 'Enter 4-digit OTP',
    'scan.title': 'Label Scanner',
    'scan.upload': 'Upload or drop a product label image',
    'scan.scan': 'Scan for Compliance',
    'scan.scanning': 'Analysing label…',
    'scan.result.compliant': 'Compliant',
    'scan.result.violation': 'Violations Found',
    'scan.result.partial': 'Partially Compliant',
    'report.generate': 'Generate Report',
    'report.pdf': 'Export as PDF',
    'report.excel': 'Export as Excel',
    'greeting.morning': 'Good morning',
    'greeting.afternoon': 'Good afternoon',
    'greeting.evening': 'Good evening',
  },
  hi: {
    'app.name': 'लीगलमेट्रो कम्पलाय',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.scanner': 'लेबल स्कैनर',
    'nav.repository': 'भंडार',
    'nav.reports': 'रिपोर्ट',
    'nav.users': 'उपयोगकर्ता प्रबंधन',
    'nav.settings': 'सेटिंग्स',
    'nav.logout': 'लॉग आउट',
    'nav.profile': 'मेरी प्रोफ़ाइल',
    'common.loading': 'लोड हो रहा है…',
    'common.error': 'कुछ गलत हो गया।',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.close': 'बंद करें',
    'common.download': 'डाउनलोड',
    'common.export': 'निर्यात',
    'common.search': 'खोजें…',
    'common.filter': 'फ़िल्टर',
    'common.refresh': 'ताज़ा करें',
    'login.heading': 'अपनी भूमिका चुनें',
    'login.subheading': 'प्रत्येक भूमिका का अलग डैशबोर्ड है।',
    'login.features': 'मुख्य विशेषताएं',
    'login.footer': 'कानूनी माप विज्ञान अधिनियम, 2009 · LM (PC) नियम, 2011 · भारत सरकार',
    'login.userId': 'उपयोक्ता आईडी',
    'login.password': 'पासवर्ड',
    'login.signIn': 'साइन इन करें',
    'login.back': 'वापस जाएं',
    'login.mobile': 'मोबाइल नंबर',
    'login.sendOtp': 'OTP भेजें',
    'login.verifyOtp': 'सत्यापित करें',
    'login.resendOtp': 'OTP पुनः भेजें',
    'login.enterOtp': '4-अंक OTP दर्ज करें',
    'scan.title': 'लेबल स्कैनर',
    'scan.upload': 'उत्पाद लेबल अपलोड करें',
    'scan.scan': 'अनुपालन जांच',
    'scan.scanning': 'लेबल विश्लेषण…',
    'scan.result.compliant': 'अनुपालित',
    'scan.result.violation': 'उल्लंघन पाए गए',
    'scan.result.partial': 'आंशिक रूप से अनुपालित',
    'report.generate': 'रिपोर्ट बनाएं',
    'report.pdf': 'PDF के रूप में निर्यात',
    'report.excel': 'Excel के रूप में निर्यात',
    'greeting.morning': 'सुप्रभात',
    'greeting.afternoon': 'नमस्कार',
    'greeting.evening': 'शुभ संध्या',
  },
  bn: {
    'app.name': 'লিগ্যালমেট্রো কমপ্লাই',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.scanner': 'লেবেল স্ক্যানার',
    'nav.repository': 'ভান্ডার',
    'nav.reports': 'প্রতিবেদন',
    'nav.users': 'ব্যবহারকারী ব্যবস্থাপনা',
    'nav.settings': 'সেটিংস',
    'nav.logout': 'লগ আউট',
    'nav.profile': 'আমার প্রোফাইল',
    'common.loading': 'লোড হচ্ছে…',
    'common.error': 'কিছু একটা ভুল হয়েছে।',
    'common.save': 'সংরক্ষণ',
    'common.cancel': 'বাতিল',
    'common.close': 'বন্ধ',
    'common.download': 'ডাউনলোড',
    'common.export': 'রপ্তানি',
    'common.search': 'অনুসন্ধান…',
    'common.filter': 'ফিল্টার',
    'common.refresh': 'রিফ্রেশ',
    'login.heading': 'আপনার ভূমিকা নির্বাচন করুন',
    'login.subheading': 'প্রতিটি ভূমিকার আলাদা ড্যাশবোর্ড রয়েছে।',
    'login.features': 'প্ল্যাটফর্ম সুবিধাসমূহ',
    'login.footer': 'আইনি মেট্রোলজি আইন, ২০০৯ · LM (PC) বিধি, ২০১১ · ভারত সরকার',
    'login.userId': 'ব্যবহারকারী আইডি',
    'login.password': 'পাসওয়ার্ড',
    'login.signIn': 'সাইন ইন',
    'login.back': 'ভূমিকা নির্বাচনে ফিরুন',
    'login.mobile': 'মোবাইল নম্বর',
    'login.sendOtp': 'OTP পাঠান',
    'login.verifyOtp': 'যাচাই করুন ও সাইন ইন',
    'login.resendOtp': 'OTP পুনরায় পাঠান',
    'login.enterOtp': '৪-সংখ্যার OTP লিখুন',
    'scan.title': 'লেবেল স্ক্যানার',
    'scan.upload': 'পণ্যের লেবেলের ছবি আপলোড করুন',
    'scan.scan': 'সম্মতি যাচাই করুন',
    'scan.scanning': 'লেবেল বিশ্লেষণ হচ্ছে…',
    'scan.result.compliant': 'সম্মত',
    'scan.result.violation': 'লঙ্ঘন পাওয়া গেছে',
    'scan.result.partial': 'আংশিকভাবে সম্মত',
    'report.generate': 'প্রতিবেদন তৈরি করুন',
    'report.pdf': 'PDF হিসেবে রপ্তানি',
    'report.excel': 'Excel হিসেবে রপ্তানি',
    'greeting.morning': 'শুভ সকাল',
    'greeting.afternoon': 'শুভ দুপুর',
    'greeting.evening': 'শুভ সন্ধ্যা',
  },
  te: {
    'app.name': 'లీగల్‌మెట్రో కంప్లై',
    'nav.dashboard': 'డ్యాష్‌బోర్డ్',
    'nav.scanner': 'లేబుల్ స్కానర్',
    'nav.repository': 'రిపాజిటరీ',
    'nav.reports': 'నివేదికలు',
    'nav.users': 'వినియోగదారు నిర్వహణ',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.logout': 'లాగ్ అవుట్',
    'nav.profile': 'నా ప్రొఫైల్',
    'common.loading': 'లోడవుతోంది…',
    'common.error': 'ఏదో తప్పు జరిగింది.',
    'common.save': 'సేవ్ చేయండి',
    'common.cancel': 'రద్దు చేయండి',
    'common.close': 'మూసివేయండి',
    'common.download': 'డౌన్‌లోడ్',
    'common.export': 'ఎగుమతి',
    'common.search': 'వెతకండి…',
    'common.filter': 'ఫిల్టర్',
    'common.refresh': 'రిఫ్రెష్',
    'login.heading': 'మీ పాత్రను ఎంచుకోండి',
    'login.subheading': 'ప్రతి పాత్రకు ప్రత్యేక డ్యాష్‌బోర్డ్ ఉంటుంది.',
    'login.features': 'ప్లాట్‌ఫారం సామర్థ్యాలు',
    'login.footer': 'చట్టపరమైన మెట్రాలజీ చట్టం, 2009 · LM (PC) నిబంధనలు, 2011 · భారత ప్రభుత్వం',
    'login.userId': 'వినియోగదారు ID',
    'login.password': 'పాస్‌వర్డ్',
    'login.signIn': 'సైన్ ఇన్',
    'login.back': 'పాత్ర ఎంపికకు తిరిగి వెళ్ళండి',
    'login.mobile': 'మొబైల్ నంబర్',
    'login.sendOtp': 'OTP పంపండి',
    'login.verifyOtp': 'ధృవీకరించి సైన్ ఇన్ చేయండి',
    'login.resendOtp': 'OTP మళ్ళీ పంపండి',
    'login.enterOtp': '4-అంకెల OTP నమోదు చేయండి',
    'scan.title': 'లేబుల్ స్కానర్',
    'scan.upload': 'ఉత్పత్తి లేబుల్ చిత్రాన్ని అప్‌లోడ్ చేయండి',
    'scan.scan': 'సమ్మతిని తనిఖీ చేయండి',
    'scan.scanning': 'లేబుల్ విశ్లేషిస్తోంది…',
    'scan.result.compliant': 'అనుగుణంగా ఉంది',
    'scan.result.violation': 'ఉల్లంఘనలు కనుగొనబడ్డాయి',
    'scan.result.partial': 'పాక్షికంగా అనుగుణంగా ఉంది',
    'report.generate': 'నివేదిక రూపొందించండి',
    'report.pdf': 'PDF గా ఎగుమతి చేయండి',
    'report.excel': 'Excel గా ఎగుమతి చేయండి',
    'greeting.morning': 'శుభోదయం',
    'greeting.afternoon': 'శుభ మధ్యాహ్నం',
    'greeting.evening': 'శుభ సాయంత్రం',
  },
  mr: {
    'app.name': 'लीगलमेट्रो कम्प्लाय',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.scanner': 'लेबल स्कॅनर',
    'nav.repository': 'भांडार',
    'nav.reports': 'अहवाल',
    'nav.users': 'वापरकर्ता व्यवस्थापन',
    'nav.settings': 'सेटिंग्ज',
    'nav.logout': 'लॉग आउट',
    'nav.profile': 'माझी प्रोफाइल',
    'common.loading': 'लोड होत आहे…',
    'common.error': 'काहीतरी चूक झाली.',
    'common.save': 'जतन करा',
    'common.cancel': 'रद्द करा',
    'common.close': 'बंद करा',
    'common.download': 'डाउनलोड',
    'common.export': 'निर्यात',
    'common.search': 'शोधा…',
    'common.filter': 'फिल्टर',
    'common.refresh': 'रिफ्रेश',
    'login.heading': 'आपली भूमिका निवडा',
    'login.subheading': 'प्रत्येक भूमिकेसाठी स्वतंत्र डॅशबोर्ड आहे.',
    'login.features': 'प्लॅटफॉर्म क्षमता',
    'login.footer': 'कायदेशीर मेट्रोलॉजी कायदा, 2009 · LM (PC) नियम, 2011 · भारत सरकार',
    'login.userId': 'वापरकर्ता ID',
    'login.password': 'पासवर्ड',
    'login.signIn': 'साइन इन करा',
    'login.back': 'भूमिका निवडीकडे परत जा',
    'login.mobile': 'मोबाइल नंबर',
    'login.sendOtp': 'OTP पाठवा',
    'login.verifyOtp': 'सत्यापित करा व साइन इन करा',
    'login.resendOtp': 'OTP पुन्हा पाठवा',
    'login.enterOtp': '4-अंकी OTP प्रविष्ट करा',
    'scan.title': 'लेबल स्कॅनर',
    'scan.upload': 'उत्पादन लेबल प्रतिमा अपलोड करा',
    'scan.scan': 'अनुपालन तपासा',
    'scan.scanning': 'लेबल विश्लेषण होत आहे…',
    'scan.result.compliant': 'अनुपालित',
    'scan.result.violation': 'उल्लंघन आढळले',
    'scan.result.partial': 'अंशतः अनुपालित',
    'report.generate': 'अहवाल तयार करा',
    'report.pdf': 'PDF म्हणून निर्यात करा',
    'report.excel': 'Excel म्हणून निर्यात करा',
    'greeting.morning': 'सुप्रभात',
    'greeting.afternoon': 'शुभ दुपार',
    'greeting.evening': 'शुभ संध्याकाळ',
  },
  ta: {
    'app.name': 'லீகல்மெட்ரோ கம்ப்லை',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.scanner': 'லேபிள் ஸ்கேனர்',
    'nav.repository': 'களஞ்சியம்',
    'nav.reports': 'அறிக்கைகள்',
    'nav.users': 'பயனர் மேலாண்மை',
    'nav.settings': 'அமைப்புகள்',
    'nav.logout': 'வெளியேறு',
    'nav.profile': 'என் சுயவிவரம்',
    'common.loading': 'ஏற்றுகிறது…',
    'common.error': 'ஏதோ தவறு நடந்தது.',
    'common.save': 'சேமி',
    'common.cancel': 'ரத்து செய்',
    'common.close': 'மூடு',
    'common.download': 'பதிவிறக்கம்',
    'common.export': 'ஏற்றுமதி',
    'common.search': 'தேடு…',
    'common.filter': 'வடிகட்டு',
    'common.refresh': 'புதுப்பி',
    'login.heading': 'உங்கள் பாத்திரத்தை தேர்ந்தெடுங்கள்',
    'login.subheading': 'ஒவ்வொரு பாத்திரத்திற்கும் தனி டாஷ்போர்டு உள்ளது.',
    'login.features': 'தளம் திறன்கள்',
    'login.footer': 'சட்டப்பூர்வ அளவியல் சட்டம், 2009 · LM (PC) விதிகள், 2011 · இந்திய அரசு',
    'login.userId': 'பயனர் ID',
    'login.password': 'கடவுச்சொல்',
    'login.signIn': 'உள்நுழை',
    'login.back': 'பாத்திரத் தேர்வுக்குத் திரும்பு',
    'login.mobile': 'மொபைல் எண்',
    'login.sendOtp': 'OTP அனுப்பு',
    'login.verifyOtp': 'சரிபார்த்து உள்நுழை',
    'login.resendOtp': 'OTP மீண்டும் அனுப்பு',
    'login.enterOtp': '4-இலக்க OTP உள்ளிடுக',
    'scan.title': 'லேபிள் ஸ்கேனர்',
    'scan.upload': 'தயாரிப்பு லேபிள் படத்தை பதிவேற்றுக',
    'scan.scan': 'இணக்கத்தை சரிபார்க்கவும்',
    'scan.scanning': 'லேபிள் பகுப்பாய்வு நடக்கிறது…',
    'scan.result.compliant': 'இணக்கமானது',
    'scan.result.violation': 'மீறல்கள் கண்டறியப்பட்டன',
    'scan.result.partial': 'பகுதியளவு இணக்கமானது',
    'report.generate': 'அறிக்கை உருவாக்கு',
    'report.pdf': 'PDF ஆக ஏற்றுமதி',
    'report.excel': 'Excel ஆக ஏற்றுமதி',
    'greeting.morning': 'காலை வணக்கம்',
    'greeting.afternoon': 'மதிய வணக்கம்',
    'greeting.evening': 'மாலை வணக்கம்',
  },
  ur: {
    'app.name': 'لیگل میٹرو کمپلائی',
    'nav.dashboard': 'ڈیش بورڈ',
    'nav.scanner': 'لیبل اسکینر',
    'nav.repository': 'ذخیرہ',
    'nav.reports': 'رپورٹیں',
    'nav.users': 'صارف انتظام',
    'nav.settings': 'ترتیبات',
    'nav.logout': 'لاگ آؤٹ',
    'nav.profile': 'میری پروفائل',
    'common.loading': 'لوڈ ہو رہا ہے…',
    'common.error': 'کچھ غلط ہو گیا۔',
    'common.save': 'محفوظ کریں',
    'common.cancel': 'منسوخ کریں',
    'common.close': 'بند کریں',
    'common.download': 'ڈاؤنلوڈ',
    'common.export': 'برآمد',
    'common.search': 'تلاش کریں…',
    'common.filter': 'فلٹر',
    'common.refresh': 'تازہ کریں',
    'login.heading': 'اپنا کردار منتخب کریں',
    'login.subheading': 'ہر کردار کا الگ ڈیش بورڈ ہے۔',
    'login.features': 'پلیٹ فارم کی خصوصیات',
    'login.footer': 'قانونی پیمائش کا قانون، 2009 · LM (PC) اصول، 2011 · حکومت ہند',
    'login.userId': 'صارف ID',
    'login.password': 'پاس ورڈ',
    'login.signIn': 'سائن ان کریں',
    'login.back': 'کردار کے انتخاب پر واپس جائیں',
    'login.mobile': 'موبائل نمبر',
    'login.sendOtp': 'OTP بھیجیں',
    'login.verifyOtp': 'تصدیق کریں اور سائن ان کریں',
    'login.resendOtp': 'OTP دوبارہ بھیجیں',
    'login.enterOtp': '4 ہندسوں کا OTP درج کریں',
    'scan.title': 'لیبل اسکینر',
    'scan.upload': 'مصنوع کا لیبل تصویر اپ لوڈ کریں',
    'scan.scan': 'تعمیل چیک کریں',
    'scan.scanning': 'لیبل تجزیہ ہو رہا ہے…',
    'scan.result.compliant': 'متوافق',
    'scan.result.violation': 'خلاف ورزیاں پائی گئیں',
    'scan.result.partial': 'جزوی طور پر متوافق',
    'report.generate': 'رپورٹ بنائیں',
    'report.pdf': 'PDF کے طور پر برآمد',
    'report.excel': 'Excel کے طور پر برآمد',
    'greeting.morning': 'صبح بخیر',
    'greeting.afternoon': 'دوپہر بخیر',
    'greeting.evening': 'شام بخیر',
  },
  gu: {
    'app.name': 'લીગલમેટ્રો કોમ્પ્લાય',
    'nav.dashboard': 'ડૅશબૉર્ડ',
    'nav.scanner': 'લેબલ સ્કૅનર',
    'nav.repository': 'ભંડાર',
    'nav.reports': 'અહેવાલ',
    'nav.users': 'વપરાશકર્તા વ્યવસ્થાપન',
    'nav.settings': 'સેટિંગ્સ',
    'nav.logout': 'લૉગ આઉટ',
    'nav.profile': 'મારી પ્રોફાઇલ',
    'common.loading': 'લોડ થઈ રહ્યું છે…',
    'common.error': 'કઈ ક ખોટું થઈ ગ્યું.',
    'common.save': 'સાચવો',
    'common.cancel': 'રદ કરો',
    'common.close': 'બંધ કરો',
    'common.download': 'ડાઉનલોડ',
    'common.export': 'નિકાસ',
    'common.search': 'શોધો…',
    'common.filter': 'ફિલ્ટર',
    'common.refresh': 'રિફ્રેશ',
    'login.heading': 'તમારી ભૂમિકા પસંદ કરો',
    'login.subheading': 'દરેક ભૂમિકા માટે અલગ ડૅશબૉર્ડ છે.',
    'login.features': 'પ્લૅટફૉર્મ ક્ષમતાઓ',
    'login.footer': 'કાનૂની માપ-વિજ્ઞાન અધિનિયમ, 2009 · LM (PC) નિયમો, 2011 · ભારત સરકાર',
    'login.userId': 'વપરાશકર્તા ID',
    'login.password': 'પાસવર્ડ',
    'login.signIn': 'સાઇન ઇન કરો',
    'login.back': 'ભૂમિકા પસંદ પર પાછા જાઓ',
    'login.mobile': 'મોબાઇલ નંબર',
    'login.sendOtp': 'OTP મોકલો',
    'login.verifyOtp': 'ચકાસો અને સાઇન ઇન કરો',
    'login.resendOtp': 'OTP ફરીથી મોકલો',
    'login.enterOtp': '4-અંકનો OTP દાખલ કરો',
    'scan.title': 'લેબલ સ્કૅનર',
    'scan.upload': 'ઉત્પાદ લેબલ ઇમેજ અપલોડ કરો',
    'scan.scan': 'અનુપાલન ચકાસો',
    'scan.scanning': 'લેબલ વિશ્લેષણ…',
    'scan.result.compliant': 'અનુપાલિત',
    'scan.result.violation': 'ઉલ્લંઘન મળ્યાં',
    'scan.result.partial': 'આંશિક રીતે અનુપાલિત',
    'report.generate': 'અહેવાલ બનાવો',
    'report.pdf': 'PDF તરીકે નિકાસ',
    'report.excel': 'Excel તરીકે નિકાસ',
    'greeting.morning': 'સુપ્રભાત',
    'greeting.afternoon': 'શુભ બપોર',
    'greeting.evening': 'શુભ સાંજ',
  },
  kn: {
    'app.name': 'ಲೀಗಲ್‌ಮೆಟ್ರೋ ಕಂಪ್ಲೈ',
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.scanner': 'ಲೇಬಲ್ ಸ್ಕ್ಯಾನರ್',
    'nav.repository': 'ಭಂಡಾರ',
    'nav.reports': 'ವರದಿಗಳು',
    'nav.users': 'ಬಳಕೆದಾರ ನಿರ್ವಹಣೆ',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav.logout': 'ಲಾಗ್ ಔಟ್',
    'nav.profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
    'common.error': 'ಏನೋ ತಪ್ಪಾಯಿತು.',
    'common.save': 'ಉಳಿಸಿ',
    'common.cancel': 'ರದ್ದು ಮಾಡಿ',
    'common.close': 'ಮುಚ್ಚಿ',
    'common.download': 'ಡೌನ್‌ಲೋಡ್',
    'common.export': 'ರಫ್ತು',
    'common.search': 'ಹುಡುಕಿ…',
    'common.filter': 'ಫಿಲ್ಟರ್',
    'common.refresh': 'ರಿಫ್ರೆಶ್',
    'login.heading': 'ನಿಮ್ಮ ಪಾತ್ರ ಆಯ್ಕೆ ಮಾಡಿ',
    'login.subheading': 'ಪ್ರತಿ ಪಾತ್ರಕ್ಕೆ ಪ್ರತ್ಯೇಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಇದೆ.',
    'login.features': 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಸಾಮರ್ಥ್ಯಗಳು',
    'login.footer': 'ಕಾನೂನು ಮೆಟ್ರಾಲಜಿ ಕಾಯಿದೆ, 2009 · LM (PC) ನಿಯಮಗಳು, 2011 · ಭಾರತ ಸರ್ಕಾರ',
    'login.userId': 'ಬಳಕೆದಾರ ID',
    'login.password': 'ಪಾಸ್‌ವರ್ಡ್',
    'login.signIn': 'ಸೈನ್ ಇನ್',
    'login.back': 'ಪಾತ್ರ ಆಯ್ಕೆಗೆ ಹಿಂತಿರುಗಿ',
    'login.mobile': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    'login.sendOtp': 'OTP ಕಳುಹಿಸಿ',
    'login.verifyOtp': 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'login.resendOtp': 'OTP ಮರುಕಳುಹಿಸಿ',
    'login.enterOtp': '4-ಅಂಕಿ OTP ನಮೂದಿಸಿ',
    'scan.title': 'ಲೇಬಲ್ ಸ್ಕ್ಯಾನರ್',
    'scan.upload': 'ಉತ್ಪನ್ನ ಲೇಬಲ್ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'scan.scan': 'ಅನುಸರಣೆ ಪರಿಶೀಲಿಸಿ',
    'scan.scanning': 'ಲೇಬಲ್ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ…',
    'scan.result.compliant': 'ಅನುಸರಣೆಯಲ್ಲಿದೆ',
    'scan.result.violation': 'ಉಲ್ಲಂಘನೆಗಳು ಕಂಡುಬಂದಿವೆ',
    'scan.result.partial': 'ಭಾಗಶಃ ಅನುಸರಣೆ',
    'report.generate': 'ವರದಿ ರಚಿಸಿ',
    'report.pdf': 'PDF ಆಗಿ ರಫ್ತು ಮಾಡಿ',
    'report.excel': 'Excel ಆಗಿ ರಫ್ತು ಮಾಡಿ',
    'greeting.morning': 'ಶುಭೋದಯ',
    'greeting.afternoon': 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    'greeting.evening': 'ಶುಭ ಸಂಜೆ',
  },
  ml: {
    'app.name': 'ലീഗൽമെട്രോ കംപ്ലൈ',
    'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',
    'nav.scanner': 'ലേബൽ സ്‌കാനർ',
    'nav.repository': 'ശേഖരം',
    'nav.reports': 'റിപ്പോർട്ടുകൾ',
    'nav.users': 'ഉപയോക്തൃ മാനേജ്‌മെന്റ്',
    'nav.settings': 'ക്രമീകരണങ്ങൾ',
    'nav.logout': 'ലോഗ് ഔട്ട്',
    'nav.profile': 'എന്റെ പ്രൊഫൈൽ',
    'common.loading': 'ലോഡ് ചെയ്യുന്നു…',
    'common.error': 'എന്തോ തെറ്റ് സംഭവിച്ചു.',
    'common.save': 'സേവ് ചെയ്യുക',
    'common.cancel': 'റദ്ദാക്കുക',
    'common.close': 'അടക്കുക',
    'common.download': 'ഡൗൺലോഡ്',
    'common.export': 'എക്‌സ്‌പോർട്ട്',
    'common.search': 'തിരയുക…',
    'common.filter': 'ഫിൽട്ടർ',
    'common.refresh': 'റിഫ്രഷ്',
    'login.heading': 'നിങ്ങളുടെ റോൾ തിരഞ്ഞെടുക്കുക',
    'login.subheading': 'ഓരോ റോളിനും പ്രത്യേക ഡാഷ്‌ബോർഡ് ഉണ്ട്.',
    'login.features': 'പ്ലാറ്റ്‌ഫോം കഴിവുകൾ',
    'login.footer': 'നിയമ മെട്രോളജി ആക്ട്, 2009 · LM (PC) ചട്ടങ്ങൾ, 2011 · ഇന്ത്യൻ സർക്കാർ',
    'login.userId': 'ഉപയോക്തൃ ID',
    'login.password': 'പാസ്‌വേഡ്',
    'login.signIn': 'സൈൻ ഇൻ',
    'login.back': 'റോൾ തിരഞ്ഞെടുക്കലിലേക്ക് തിരിച്ചുപോകുക',
    'login.mobile': 'മൊബൈൽ നമ്പർ',
    'login.sendOtp': 'OTP അയക്കുക',
    'login.verifyOtp': 'സ്ഥിരീകരിക്കുക & സൈൻ ഇൻ',
    'login.resendOtp': 'OTP വീണ്ടും അയക്കുക',
    'login.enterOtp': '4-അക്ക OTP നൽകുക',
    'scan.title': 'ലേബൽ സ്‌കാനർ',
    'scan.upload': 'ഉൽപ്പന്ന ലേബൽ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    'scan.scan': 'അനുസരണം പരിശോധിക്കുക',
    'scan.scanning': 'ലേബൽ വിശകലനം ചെയ്യുന്നു…',
    'scan.result.compliant': 'അനുസരണമുണ്ട്',
    'scan.result.violation': 'ലംഘനങ്ങൾ കണ്ടെത്തി',
    'scan.result.partial': 'ഭാഗികമായി അനുസരണം',
    'report.generate': 'റിപ്പോർട്ട് സൃഷ്ടിക്കുക',
    'report.pdf': 'PDF ആയി എക്‌സ്‌പോർട്ട്',
    'report.excel': 'Excel ആയി എക്‌സ്‌പോർട്ട്',
    'greeting.morning': 'സുപ്രഭാതം',
    'greeting.afternoon': 'ശുഭ ഉച്ചക്ക്',
    'greeting.evening': 'ശുഭ സന്ധ്യ',
  },
  pa: {
    'app.name': 'ਲੀਗਲਮੈਟਰੋ ਕੰਪਲਾਈ',
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.scanner': 'ਲੇਬਲ ਸਕੈਨਰ',
    'nav.repository': 'ਭੰਡਾਰ',
    'nav.reports': 'ਰਿਪੋਰਟਾਂ',
    'nav.users': 'ਉਪਭੋਗਤਾ ਪ੍ਰਬੰਧਨ',
    'nav.settings': 'ਸੈਟਿੰਗਾਂ',
    'nav.logout': 'ਲੌਗ ਆਉਟ',
    'nav.profile': 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…',
    'common.error': 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ।',
    'common.save': 'ਸੁਰੱਖਿਅਤ ਕਰੋ',
    'common.cancel': 'ਰੱਦ ਕਰੋ',
    'common.close': 'ਬੰਦ ਕਰੋ',
    'common.download': 'ਡਾਊਨਲੋਡ',
    'common.export': 'ਨਿਰਯਾਤ',
    'common.search': 'ਖੋਜੋ…',
    'common.filter': 'ਫਿਲਟਰ',
    'common.refresh': 'ਰਿਫ੍ਰੈਸ਼',
    'login.heading': 'ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ',
    'login.subheading': 'ਹਰ ਭੂਮਿਕਾ ਦਾ ਵੱਖਰਾ ਡੈਸ਼ਬੋਰਡ ਹੈ।',
    'login.features': 'ਪਲੇਟਫਾਰਮ ਸਮਰੱਥਾਵਾਂ',
    'login.footer': 'ਕਾਨੂੰਨੀ ਮਾਪ ਵਿਗਿਆਨ ਐਕਟ, 2009 · LM (PC) ਨਿਯਮ, 2011 · ਭਾਰਤ ਸਰਕਾਰ',
    'login.userId': 'ਉਪਭੋਗਤਾ ID',
    'login.password': 'ਪਾਸਵਰਡ',
    'login.signIn': 'ਸਾਈਨ ਇਨ ਕਰੋ',
    'login.back': 'ਭੂਮਿਕਾ ਚੋਣ \'ਤੇ ਵਾਪਸ ਜਾਓ',
    'login.mobile': 'ਮੋਬਾਈਲ ਨੰਬਰ',
    'login.sendOtp': 'OTP ਭੇਜੋ',
    'login.verifyOtp': 'ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਸਾਈਨ ਇਨ ਕਰੋ',
    'login.resendOtp': 'OTP ਦੁਬਾਰਾ ਭੇਜੋ',
    'login.enterOtp': '4-ਅੰਕ OTP ਦਰਜ ਕਰੋ',
    'scan.title': 'ਲੇਬਲ ਸਕੈਨਰ',
    'scan.upload': 'ਉਤਪਾਦ ਲੇਬਲ ਚਿੱਤਰ ਅਪਲੋਡ ਕਰੋ',
    'scan.scan': 'ਪਾਲਣਾ ਦੀ ਜਾਂਚ ਕਰੋ',
    'scan.scanning': 'ਲੇਬਲ ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ…',
    'scan.result.compliant': 'ਅਨੁਕੂਲ',
    'scan.result.violation': 'ਉਲੰਘਣਾਵਾਂ ਮਿਲੀਆਂ',
    'scan.result.partial': 'ਅੰਸ਼ਿਕ ਤੌਰ ਤੇ ਅਨੁਕੂਲ',
    'report.generate': 'ਰਿਪੋਰਟ ਬਣਾਓ',
    'report.pdf': 'PDF ਵਜੋਂ ਨਿਰਯਾਤ',
    'report.excel': 'Excel ਵਜੋਂ ਨਿਰਯਾਤ',
    'greeting.morning': 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ',
    'greeting.afternoon': 'ਸ਼ੁਭ ਦੁਪਹਿਰ',
    'greeting.evening': 'ਸ਼ੁਭ ਸ਼ਾਮ',
  },
};

function t(key, lang) {
  const l = lang || localStorage.getItem('lm_lang') || 'en';
  return STRINGS[l]?.[key] || STRINGS.en?.[key] || key;
}
